# Generated by Django 3.0.8 on 2020-08-09 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='negotiable',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
