# Generated by Django 3.0.8 on 2020-08-09 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('Kumasi', 'Kumasi'), ('Accra', 'Accra'), ('Takoradi', 'Takoradi')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
